### ISSUE TITLE
Blank category being saved when creating a transaction of type income

### ISSUE THREAD

**Issue by squarepear** [Free-My-Financials/free-my-financials#54]
A category with no name is created the first time you select create custom category. This should probably be fixed both client and server side.

Client side:
Don't request the creation of this empty category. This might not actually be what's happening, but it should be checked.

Server side:
Validate the user input for category creation. Currently, no input validation is run server side. This should be relatively simple with zod in the trpc router.

<img width="233" alt="Screenshot 2024-01-25 at 1 11 03 PM" src="https://github.com/Free-My-Financials/free-my-financials/assets/16364318/8bb3c053-d703-4bd9-99db-085e2cf6d310">

**Comment by Kroll-man** [comment]
it seems to not create the blank category on my windows machine using the edge browser,

**Comment by squarepear** [comment]
I believe I found the cause of the issue. It has to do with creating transactions. Currently, transactions are created with an empty category name. This leads to the creation of a category with the name "". We will likely have to rethink the way income and categories are classified to fix this.

**Comment by Kroll-man** [comment]
it honestly might have something to do with income transactions just not being labeled with a category. since it looks like all transactions have to have one on the Prisma schema. Maybe just giving them a category might fix it?
