### ISSUE TITLE
Refreshing on /budget/budget causes loss of store data

### ISSUE THREAD

**Issue by squarepear** [Free-My-Financials/free-my-financials#55]
Refreshing on the view budget page causes a warning in the console and clears store information until reloaded on a different page. Have not yet investigated the cause of this issue.

This is the warning that is shown in the web console when this is done.
`[Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.`

And this warning is shown in the server console
`[Vue warn]: onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.`

**Comment by PandorasGit** [comment]
is it just budget/budget does budget/editBudget also have problems? Might help explain why
